# Generated by Django 4.1.3 on 2022-12-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsstory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.URLField(default='https://images.unsplash.com/photo-1475518845976-0fd87b7e4e5d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8Z3JlZW4lMjBza3l8ZW58MHx8MHx8&w=1000&q=80', max_length=1000),
        ),
    ]
